# Generated by Django 6.1.1 on 2026-09-14 19:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_proveedor_direccion_proveedor_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorteCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('cerrado', models.BooleanField(default=False)),
                ('total_ventas', models.IntegerField(default=0)),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('ganancia_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.AddField(
            model_name='venta',
            name='corte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='ventas.cortecaja'),
        ),
    ]
