# Generated by Django 6.1.1 on 2026-09-14 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_cortecaja_options_alter_detalleventa_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='corte',
            field=models.ForeignKey(blank=True, help_text='Corte de caja al que pertenece esta venta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='ventas.cortecaja'),
        ),
    ]
