# Generated by Django 6.1.1 on 2026-09-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_categoria_alter_producto_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='referencia_pago',
            field=models.CharField(blank=True, help_text='Número de autorización, voucher de tarjeta o folio/rastreo de transferencia', max_length=100, null=True),
        ),
    ]
